// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkSmulYnKP-LuKsnRsJM1Cn1memVN_Dc8',
    appId: '1:992579552722:web:ed89ee22dbd8664b65f40b',
    messagingSenderId: '992579552722',
    projectId: 'heredograma-ici-118b3',
    authDomain: 'heredograma-ici-118b3.firebaseapp.com',
    storageBucket: 'heredograma-ici-118b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-gekiYjDrqI7uBxgKQqbRiDj2G4gBtdQ',
    appId: '1:992579552722:android:9740b7b05813a35765f40b',
    messagingSenderId: '992579552722',
    projectId: 'heredograma-ici-118b3',
    storageBucket: 'heredograma-ici-118b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4wWRezag9v2RYhv6kxvbzOR8Aemqbvtw',
    appId: '1:992579552722:ios:eaa271c2a1600f1665f40b',
    messagingSenderId: '992579552722',
    projectId: 'heredograma-ici-118b3',
    storageBucket: 'heredograma-ici-118b3.firebasestorage.app',
    iosBundleId: 'com.example.heredogramaIci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4wWRezag9v2RYhv6kxvbzOR8Aemqbvtw',
    appId: '1:992579552722:ios:eaa271c2a1600f1665f40b',
    messagingSenderId: '992579552722',
    projectId: 'heredograma-ici-118b3',
    storageBucket: 'heredograma-ici-118b3.firebasestorage.app',
    iosBundleId: 'com.example.heredogramaIci',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkSmulYnKP-LuKsnRsJM1Cn1memVN_Dc8',
    appId: '1:992579552722:web:676ef4bf35f6d52365f40b',
    messagingSenderId: '992579552722',
    projectId: 'heredograma-ici-118b3',
    authDomain: 'heredograma-ici-118b3.firebaseapp.com',
    storageBucket: 'heredograma-ici-118b3.firebasestorage.app',
  );
}
